### ISSUE TITLE
Crash happen while deleting the notification in the notification tab in the mysurveys app(Samsung Galaxy S7)

### ISSUE THREAD

**Issue by dinesh-opg** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#43]
MySurveys App version - 2.0.3
FATAL EXCEPTION: main
                                                                    Process: com.opg.my.surveys, PID: 14877
                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorListenerCompat;
                                                                        at com.opg.my.surveys.Fragments.NotificationsFragment.onCreateView(NotificationsFragment.java:152)
                                                                        at com.opg.my.surveys.Fragments.NotificationsFragment.onCreateView(NotificationsFragment.java:112)
                                                                        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                                        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
                                                                        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
                                                                        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                                        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
                                                                        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3231)
                                                                        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181)
                                                                        at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2276)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1442)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750)
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819)
                                                                        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
                                                                        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
                                                                        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
                                                                        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
                                                                        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
                                                                        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                                                                        at android.os.Handler.handleCallback(Handler.java:751)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                                     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.animation.AnimatorListenerCompat" on path: DexPathList[[zip file "/data/app/com.opg.my.surveys-1/base.apk"],nativeLibraryDirectories=[/data/app/com.opg.my.surveys-1/lib/arm64, /system/lib64, /vendor/lib64]]
                                                                        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                        at com.opg.my.surveys.Fragments.NotificationsFragment.onCreateView(NotificationsFragment.java:152) 
                                                                        at com.opg.my.surveys.Fragments.NotificationsFragment.onCreateView(NotificationsFragment.java:112) 
                                                                        at android.support.v4.app.Fragment.performCreateView(Fragment.java:2261) 
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419) 
                                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750) 
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819) 
                                                                        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797) 
                                                                        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590) 
                                                                        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377) 
                                                                        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332) 
                                                                        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239) 
                                                                        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3231) 
                                                                        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3181) 
                                                                        at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2276) 
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1442) 
                                                                        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1750) 
                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1819) 
                                                                        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797) 
                                                                        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590) 
                                                                        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377) 
                                                                        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332) 
                                                                        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239) 
                                                                        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700) 
                                                                        at android.os.Handler.handleCallback(Handler.java:751) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                        at android.os.Looper.loop(Looper.java:154) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6692) 
                                                                        at java.lang.reflect.Method.invoke(Native Method) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by dinesh-opg** [comment]
Thsi issue with the update in the libraries.It is fixed after updating the libraries to latest version.
