### ISSUE TITLE
MySurveys app is crashing when starting geofence monitoring (Samsung Galaxy Fame S6810)

### ISSUE THREAD

**Issue by NeerajOPG** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#44]
Device specification/configuration:
Device Model: Samsung Galaxy Fame S6810
Android OS Version - 4.1.2
RAM - 512 MB
MySurveys Vesion - 2.0.3
12-27 12:01:14.452 7359-7359/com.opg.my.surveys E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  java.lang.RuntimeException: Unable to stop service com.opg.my.surveys.LocationService@422e5be0: java.lang.NullPointerException: GoogleApiClient must not be null
                                                                      at android.app.ActivityThread.handleStopService(ActivityThread.java:2615)
                                                                      at android.app.ActivityThread.access$2100(ActivityThread.java:140)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1346)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                      at android.os.Looper.loop(Looper.java:137)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:4944)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:511)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
                                                                      at dalvik.system.NativeStart.main(Native Method)
                                                                   Caused by: java.lang.NullPointerException: GoogleApiClient must not be null
                                                                      at com.google.android.gms.common.internal.zzac.zzb(Unknown Source)
                                                                      at com.google.android.gms.internal.zzzv$zza.<init>(Unknown Source)
                                                                      at com.google.android.gms.location.LocationServices$zza.<init>(Unknown Source)
                                                                      at com.google.android.gms.internal.zzarl$zza.<init>(Unknown Source)
                                                                      at com.google.android.gms.internal.zzarl$9.<init>(Unknown Source)
                                                                      at com.google.android.gms.internal.zzarl.removeLocationUpdates(Unknown Source)
                                                                      at com.opg.my.surveys.LocationService.stopLocationUpdates(LocationService.java:242)
                                                                      at com.opg.my.surveys.LocationService.onDestroy(LocationService.java:558)
                                                                      at android.app.ActivityThread.handleStopService(ActivityThread.java:2598)
                                                                      at android.app.ActivityThread.access$2100(ActivityThread.java:140) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1346) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                      at android.os.Looper.loop(Looper.java:137) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:4944) 
                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805) 
                                                                      at dalvik.system.NativeStart.main(Native Method) 
12-27 12:01:18.787 7359-7515/com.opg.my.surveys E/dalvikvm-heap: Out of memory on a 20472514-byte allocation.

**Comment by NeerajOPG** [comment]
we have added condition to check whether GooglePlayServices is updated or  in device before starting geofence monitoring.

**Comment by NeerajOPG** [comment]
The issue is fixed in 2.0.4.

**Comment by onepointpb** [comment]
Verified.
